# Generated by Django 5.1.7 on 2025-03-11 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('designs', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='saved_designs',
            field=models.ManyToManyField(related_name='saved_by_buyers', to='designs.design'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyer',
            name='preferences',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.buyerpreferences'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contactinfo'),
        ),
        migrations.AddField(
            model_name='designer',
            name='portfolio',
            field=models.ManyToManyField(related_name='designer_portfolio', to='designs.design'),
        ),
        migrations.AddField(
            model_name='designer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factorypartner',
            name='factory_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.factorydetails'),
        ),
        migrations.AddField(
            model_name='factorypartner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factorypartner',
            name='waste_inventory',
            field=models.ManyToManyField(to='inventory.textilewaste'),
        ),
    ]
