# Generated by Django 5.1.7 on 2025-03-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('FACTORY', 'Factory Partner'), ('DESIGNER', 'Designer'), ('BUYER', 'Buyer')], max_length=20),
        ),
    ]
