# Generated by Django 5.1.7 on 2025-03-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorydetails',
            name='factory_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='factorydetails',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factorydetails',
            name='production_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
