# Generated by Django 5.1.7 on 2025-03-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_fix_factory_user_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factorydetails',
            options={'verbose_name_plural': 'Factory Details'},
        ),
    ]
