# Generated by Django 5.1.7 on 2025-03-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_factorydetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
