# Generated by Django 5.1.7 on 2025-03-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_designer_approval_date_designer_is_approved'),
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='design_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='designer',
            name='portfolio',
            field=models.ManyToManyField(blank=True, related_name='designer_portfolio', to='designs.design'),
        ),
    ]
