# Generated by Django 5.1.7 on 2025-04-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_designer_design_stats_alter_designer_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('FACTORY', 'Factory Partner'), ('DESIGNER', 'Designer'), ('BUYER', 'Buyer'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
