# Generated by Django 5.1.7 on 2025-03-11 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TextileWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_id', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('USED', 'Used'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20)),
                ('dimensions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.dimensions')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_items', to='accounts.factorypartner')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
