# Generated by Django 5.1.7 on 2025-03-18 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textilewaste',
            options={'ordering': ['-date_added'], 'permissions': [('can_review_waste', 'Can review waste entries'), ('can_manage_inventory', 'Can manage inventory'), ('can_view_analytics', 'Can view inventory analytics')]},
        ),
        migrations.AddField(
            model_name='textilewaste',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='textilewaste',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='textilewaste',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textilewaste',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='textilewaste',
            name='quality_grade',
            field=models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=20),
        ),
        migrations.AddField(
            model_name='textilewaste',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_waste', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textilewaste',
            name='storage_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='textilewaste',
            name='sustainability_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='textilewaste',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='textilewaste',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('PENDING_REVIEW', 'Pending Review')], default='PENDING_REVIEW', max_length=20),
        ),
        migrations.CreateModel(
            name='WasteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('PENDING_REVIEW', 'Pending Review')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('waste_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.textilewaste')),
            ],
            options={
                'verbose_name_plural': 'Waste histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
