# Generated by Django 5.1.7 on 2025-03-26 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_design_image'),
        ('inventory', '0003_alter_textilewaste_options_textilewaste_batch_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='customization_options',
        ),
        migrations.RemoveField(
            model_name='design',
            name='images',
        ),
        migrations.RemoveField(
            model_name='design',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_options', to='designs.design'),
        ),
        migrations.AddField(
            model_name='design',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='design',
            name='estimated_delivery_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='design',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='design',
            name='required_materials',
            field=models.ManyToManyField(related_name='designs_requiring', to='inventory.textilewaste'),
        ),
        migrations.AlterField(
            model_name='design',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='DRAFT', max_length=20),
        ),
    ]
