# Generated by Django 5.1.7 on 2025-04-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_remove_design_customization_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='date_updated',
            new_name='last_modified',
        ),
    ]
