# Generated by Django 5.1.7 on 2025-04-18 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_designer_design_stats_alter_designer_portfolio'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        # No operations: already applied in initial schema
    ]
