# Generated by Django 5.1.7 on 2025-04-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_create_notification_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('waste_approved', 'Waste Approved'), ('waste_rejected', 'Waste Rejected'), ('order_status_update', 'Order Status Update'), ('payment_approved', 'Payment Approved')], default='info', max_length=30),
        ),
    ]
